import React,{useState,useEffect} from 'react'
import {Loader,Card,FormField } from '../components'

const Home = () => {
const [loading, setLoading] = useState(true)
const [allPost, setAllPost] = useState(null)


  return (
    <section className='max-w-7xl mx-auto'>
        <div >
            <h1 className='font-extrabold text-[#222328] text-[32px]'>
                Community ShowCase
            </h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
                Browse Throught a colllection of imaginative and visually stunning images generated by the DALL-E AI.
            </p>
        </div>

        <div className='mt-16'>
            <FormField/>

        </div>

        <div className='mt-10'>
            {loading ? (
                <div className='flex justify-center items-center'>
                    <Loader/>
                </div>
            ) : (
                <>

                </>
            )}
            
        </div>
    </section>
  )
}

export default Home